version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://your-rds-endpoint:5432/league
      DB_USER: your-db-user
      DB_PASSWORD: your-db-pass
      CLOUDWATCH_ACCESS_KEY: your-access-key
      CLOUDWATCH_SECRET_KEY: your-secret-key
      AWS_REGION: us-east-1
    logging:
      driver: awslogs
      options:
        awslogs-group: league-app-logs
        awslogs-region: us-east-1
        awslogs-stream: league-app
